#!/usr/bin/env python3
"""apply_rotation_pit.py -- sp500 PIT mode for the rotation test (free path a).

Run from the primordial repo root:  python3.10 apply_rotation_pit.py
Anchored edits; aborts writing nothing on any mismatch. Idempotent."""
import os, sys

def patch(path, old, new, label):
    s = open(path).read()
    if new in s:
        print(f"  = {label}: already applied"); return
    if old not in s or s.count(old) != 1:
        sys.exit(f"ANCHOR problem in {path} ({label}) -- aborting, nothing written.")
    open(path, "w").write(s.replace(old, new)); print(f"  + {label}")

P = "scripts/test_weekly_rotation.py"
if not os.path.exists(P):
    sys.exit("run from the primordial repo root.")
if not os.path.exists("manifests/sp500_pit_membership.csv"):
    sys.exit("manifests/sp500_pit_membership.csv missing -- it shipped with the distress PIT test.")
patch(P, "_FILES = {\"sp400\": (\"sp400_symbols.txt\", \"equity_midcap\"),", "_FILES = {\"sp500pit\": (None, \"equity_liquid\"),   # PIT membership CSV\n          \"sp400\": (\"sp400_symbols.txt\", \"equity_midcap\"),", "register sp500pit universe")
patch(P, "def _load_symbols(name):\n    fn, tier = _FILES[name]", "def _pit_csv():\n    return os.path.join(os.path.dirname(os.path.dirname(\n        os.path.abspath(__file__))), \"manifests\", \"sp500_pit_membership.csv\")\n\n\ndef _load_membership():\n    \"\"\"fja05680/sp500 point-in-time record -> (member_on(ts,sym), current).\"\"\"\n    import csv as _csv\n    from bisect import bisect_right\n    rows = [r for r in _csv.reader(open(_pit_csv()))][1:]\n    ds = [r[0] for r in rows]\n    sets_ = [frozenset(t.strip().replace(\".\", \"-\") for t in r[1].split(\",\"))\n             for r in rows]\n\n    def member(ts, sym, _ds=ds, _s=sets_):\n        i = bisect_right(_ds, str(pd.Timestamp(ts).date())) - 1\n        return i >= 0 and sym in _s[i]\n    return member, sorted(sets_[-1])\n\n\ndef _load_symbols(name):\n    fn, tier = _FILES[name]\n    if name == \"sp500pit\":\n        import csv as _csv\n        rows = [r for r in _csv.reader(open(_pit_csv()))][1:]\n        return sorted({t.strip().replace(\".\", \"-\")\n                       for r in rows for t in r[1].split(\",\")}), tier", "PIT membership loader + universe loader")
patch(P, "TICKERS, COST_TIER = _load_symbols(UNIV)", "TICKERS, COST_TIER = _load_symbols(UNIV)\n# sp500pit only -- MEMBERSHIP=pit gates entries by membership on signal date\n# (departed names included); MEMBERSHIP=today restricts to the final snapshot\n# with no gating (the survivor-biased reference, reproduced on purpose).\nMEMBERSHIP = os.environ.get(\"MEMBERSHIP\", \"pit\")\n_MEMBER, _DEPARTED = None, None\nif UNIV == \"sp500pit\":\n    _member_fn, _current = _load_membership()\n    if MEMBERSHIP == \"today\":\n        TICKERS = [t for t in TICKERS if t in set(_current)]\n        _DEPARTED = set()\n    else:\n        _MEMBER = _member_fn\n        _DEPARTED = set(TICKERS) - set(_current)", "membership mode globals")
patch(P, "        pool = allowed if allowed is not None else close.columns", "        pool = ((allowed(t_sig) if callable(allowed) else allowed)\n                if allowed is not None else close.columns)", "run_strategy: date-dependent eligibility")
patch(P, "def real_picker(s_row, elig, rng):\n    ranked = sorted(elig, key=lambda t: float(s_row[t]), reverse=True)\n    top = ranked[:TOP_N]", "PICK_LOG = []                       # real rule's picks (teeth stat for PIT)\n\n\ndef real_picker(s_row, elig, rng):\n    ranked = sorted(elig, key=lambda t: float(s_row[t]), reverse=True)\n    top = ranked[:TOP_N]\n    PICK_LOG.append(list(top))", "pick log for departed-participation stat")
patch(P, "    close, open_ = load_prices()\n    print(f\"loaded {close.shape[1]} tickers, {len(close)} sessions\")", "    close, open_ = load_prices()\n    print(f\"loaded {close.shape[1]} tickers, {len(close)} sessions\")\n\n    def GATE(lst=None):\n        \"\"\"PIT: wrap an eligibility list so membership is checked on the\n        signal date. Non-PIT: passthrough (returns lst unchanged).\"\"\"\n        if _MEMBER is None:\n            return lst\n        base_ = list(close.columns) if lst is None else list(lst)\n\n        def _fn(ts, _b=base_):\n            return [t for t in _b if _MEMBER(ts, t)]\n        return _fn\n    if _DEPARTED:\n        have = [t for t in close.columns if t in _DEPARTED]\n        print(f\"  PIT: {len(_DEPARTED)} departed names in universe | \"\n              f\"{len(have)} with price data \"\n              f\"({len(have) / max(1, len(_DEPARTED)):.0%} coverage; missing \"\n              f\"ones skew bankruptcy-profile -- momentum picks those \"\n              f\"rarely, so the hole bites less here than in distress)\")", "GATE helper + departed coverage print")
patch(P, "    r_real, npos, turn, swaps = run_strategy(close, open_, score, vol, dates,\n                                             real_picker)", "    r_real, npos, turn, swaps = run_strategy(close, open_, score, vol, dates,\n                                             real_picker, allowed=GATE())\n    if _DEPARTED:\n        slots = [t for pk in PICK_LOG for t in pk]\n        dep = sum(1 for t in slots if t in _DEPARTED) / max(1, len(slots))\n        print(f\"  PIT teeth: departed names fill {dep:.1%} of position-\"\n              f\"slots (registered: < 5% -> UNINFORMATIVE, buy the data)\")", "gate the real run + teeth stat")
patch(P, "lambda s, e, g: list(e))", "lambda s, e, g: list(e), allowed=GATE())", "gate the equal-weight reference")
patch(P, "MatchedPicker(swaps), seed=k)", "MatchedPicker(swaps), seed=k,\n                                    allowed=GATE())", "gate the matched null")
patch(P, "random_picker, seed=k)", "random_picker, seed=k,\n                                   allowed=GATE())", "gate the unmatched null")
patch(P, "real_picker, allowed=list(allowed))", "real_picker, allowed=GATE(list(allowed)))", "gate LOO/subsample runs")
patch(P, "signal to see how much of a result is just paying the spread less often.\n\"\"\"", "signal to see how much of a result is just paying the spread less often.\n\nSP500 PIT MODE (registered 2026-08-11, commit before running; two runs, one\nlook each):\n\n    UNIV=sp500pit MEMBERSHIP=today REBAL=monthly python3.10 scripts/test_weekly_rotation.py\n    UNIV=sp500pit MEMBERSHIP=pit   REBAL=monthly python3.10 scripts/test_weekly_rotation.py\n\nPurpose: does the SHAPE (composite-ROC top-N inverse-vol monthly rotation)\nsurvive restoring dead names, on the one universe with a free point-in-time\nrecord? Ground caveat: sp500, not sp400 -- decisive only in the kill\ndirection for the sp400 claim; a pass leaves Norgate as the final word.\n\nREGISTERED READING (holdout z vs matched null, the same number the sp400\nverdict used):\n  UNINFORMATIVE  departed names fill < 5% of the PIT run's position-slots\n                 -> the test has no teeth here; only Norgate can answer.\n  BIAS-DRIVEN    survivor run >= +2.0 sd AND PIT run < +1.0 sd\n                 -> survivorship is load-bearing for this shape; the sp400\n                 +2.72 sd is presumed inflated until re-run on Norgate.\n  SHAPE ROBUST   PIT run >= +2.0 sd AND regime verdict is not the\n                 one-regime warning -> the sp400 result stays provisionally\n                 credible; Norgate remains required before any capital.\n  else           INCONCLUSIVE -> Norgate decides, on the rotation's merits.\nThese two runs are looks #13-14 on the rotation family (TRIALS env already\ndefaults to 12; use TRIALS=14 for the bar line).\n\"\"\"", "registered PIT protocol in docstring")

print("\nCommit, then the two registered runs (survivor first):")
print("  UNIV=sp500pit MEMBERSHIP=today REBAL=monthly TRIALS=14 python3.10 " + P)
print("  UNIV=sp500pit MEMBERSHIP=pit   REBAL=monthly TRIALS=14 python3.10 " + P)
