"""
Scan every runs/*/run.json and build the survivor registry the project never
had: one table of everything ever tested, PASS or REJECT, with the gate that
killed it. Optionally writes SURVIVORS.md.

    python3.10 scripts/list_survivors.py            # print table
    python3.10 scripts/list_survivors.py --write    # also write SURVIVORS.md
"""
import argparse
import glob
import json
import os
import statistics

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def killer(r):
    if r.get("survived"):
        return "-"
    med = r.get("holdout_median_sharpe", 0) or 0
    bar = r.get("luck_bar", 0) or 0
    if med <= bar:
        return "bar"
    if (r.get("holdout_psr") or 0) < 0.95:
        return "PSR"
    b = r.get("breadth")
    if b and b.get("p", 1) > 0.05:
        return "breadth"
    cs = r.get("cost_stress_sharpes")
    if cs and min(cs) <= 0:
        return "cost"
    bs = r.get("bootstrap_sharpes")
    if bs:
        m = statistics.median(bs)
        if not (m > 0.5 * med or m > max(1.0, bar)):
            return "bootstrap"
    return "gate"


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--write", action="store_true")
    p.add_argument("--all", action="store_true",
                   help="include rejects in SURVIVORS.md too")
    a = p.parse_args()
    rows = []
    for f in sorted(glob.glob(os.path.join(ROOT, "runs", "*", "run.json"))):
        try:
            d = json.load(open(f))
        except Exception:
            continue
        ts = os.path.basename(os.path.dirname(f))
        man = os.path.basename(str(d.get("manifest", "?"))).replace(
            ".yaml", "")
        for r in d.get("report", []) or []:
            rows.append(dict(
                ts=ts, manifest=man, fp=str(d.get("fingerprint", ""))[:8],
                sr=r.get("holdout_median_sharpe", 0) or 0,
                bar=r.get("luck_bar", 0) or 0,
                surv=bool(r.get("survived")), kill=killer(r),
                genome=(r.get("genome", "?"))[:64]))
    if not rows:
        print("no runs/*/run.json found")
        return
    passes = [r for r in rows if r["surv"]]
    print(f"{len(rows)} candidates across {len(set(r['ts'] for r in rows))} "
          f"runs | {len(passes)} PASSED\n")
    print(f"{'date/run':<22} {'universe':<22} {'SR':>6} {'bar':>6} "
          f"{'verdict':<9} {'killed by':<10} genome")
    for r in rows:
        v = "PASS" if r["surv"] else "reject"
        print(f"{r['ts']:<22} {r['manifest']:<22} {r['sr']:>+6.2f} "
              f"{r['bar']:>+6.2f} {v:<9} {r['kill']:<10} {r['genome']}")
    if a.write:
        out = os.path.join(ROOT, "SURVIVORS.md")
        with open(out, "w") as f:
            f.write("# Survivor registry (auto-generated by "
                    "scripts/list_survivors.py)\n\n")
            f.write("Every gauntlet PASS on record. A pass is NOT a deployable "
                    "edge:\nit still owes replication on fresh ground, a "
                    "point-in-time re-test,\nand a forward test. Rejections "
                    "live in runs/*/report.html.\n\n")
            f.write("| run | universe | holdout SR | bar | genome |\n")
            f.write("|---|---|---|---|---|\n")
            for r in (rows if a.all else passes):
                mark = "" if r["surv"] else " *(reject: %s)*" % r["kill"]
                f.write(f"| {r['ts']} | {r['manifest']} | {r['sr']:+.2f} | "
                        f"{r['bar']:+.2f} | `{r['genome']}`{mark} |\n")
        print(f"\nwrote {out} ({len(rows) if a.all else len(passes)} rows)")


if __name__ == "__main__":
    main()
